### Types:
#### Ordinal Encoding
#### One-Hot Encoding
#### Dummy Variable Encoding

In [1]:
# example of a ordinal encoding
from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder

# define data
data = asarray([['red'], ['green'], ['blue']])

# define ordinal encoding
encoder = OrdinalEncoder()

# transform data
result = encoder.fit_transform(data)
print(result)

[[2.]
 [1.]
 [0.]]


In [8]:
# example of one hot encoding
from sklearn.preprocessing import OneHotEncoder

# define data
data = asarray([['red'], ['green'], ['blue']])
print(data)

# define one hot encoding
encoder = OneHotEncoder(sparse=False)

#transform data
onehot = encoder.fit_transform(data)
print(onehot)
print(onehot[0])
print(onehot[0][2])
print(type(onehot[0][0]))

[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[0. 0. 1.]
1.0
<class 'numpy.float64'>
